
// hotkeys
export const PUT_USER_FORM = 'PUT_USER_FORM';

// main
export const APP_HAS_ERRORED = 'APP_HAS_ERRORED';
export const APP_IS_LOADING = 'APP_IS_LOADING';
export const APP_USER = 'APP_USER';
export const PUT_APP_MODE = 'PUT_APP_MODE';
export const PUT_CALLCENTERS = 'PUT_CALLCENTERS';
export const PUT_STATIONS = 'PUT_STATIONS';
export const CURRENT_DATE_TIME = 'CURRENT_DATE_TIME';
export const CURRENT_DATE_TIME_CLEAR = 'CURRENT_DATE_TIME_CLEAR';
export const CURRENT_WORK_DAY = 'CURRENT_WORK_DAY';
export const CURRENT_DUTY_NUMBER = 'CURRENT_DUTY_NUMBER';

// drill
export const PUT_DRILL_STATS = 'PUT_DRILL_STATS';
export const PUT_DRILL_STATIONS = 'PUT_DRILL_STATIONS';
export const SELECT_DRILL_STATION = 'SELECT_DRILL_STATION';
export const SELECT_DRILL_STATION_FLAG = 'SELECT_DRILL_STATION_FLAG';
export const PUT_DRILL_DUTIES = 'PUT_DRILL_DUTIES';
export const PUT_DRILL_DUTY_CURRENT_SET = 'PUT_DRILL_DUTY_CURRENT_SET';
export const PUT_DRILL_DUTY_CURRENT_ITEM = 'PUT_DRILL_DUTY_CURRENT_ITEM';
export const PUT_DRILL_DUTIES_CARS = 'PUT_DRILL_DUTIES_CARS';
export const PUT_DRILL_DUTY_CARS_CURRENT_SET = 'PUT_DRILL_DUTY_CARS_CURRENT_SET';
export const PUT_DRILL_DUTY_CARS_CURRENT_ITEM = 'PUT_DRILL_DUTY_CARS_CURRENT_ITEM';
export const PUT_DRILL_CARS = 'PUT_DRILL_CARS';
export const PUT_DRILL_CARS_CURRENT_SET = 'PUT_DRILL_CARS_CURRENT_SET';
export const PUT_DRILL_ABSENT_CARS = 'PUT_DRILL_ABSENT_CARS';
export const PUT_DRILL_ABSENT_CARS_CURRENT_SET = 'PUT_DRILL_ABSENT_CARS_CURRENT_SET';
export const PUT_DRILL_TASKS_CARS = 'PUT_DRILL_TASKS_CARS';
export const PUT_DRILL_TASKS_CARS_CURRENT_SET = 'PUT_DRILL_TASKS_CARS_CURRENT_SET';
export const PUT_DRILL_CARS_BLOCK_EDIT_STAFF_BUSY = 'PUT_DRILL_CARS_BLOCK_EDIT_STAFF_BUSY';
export const PUT_DRILL_CARS_BLOCK_VIEW = 'PUT_DRILL_CARS_BLOCK_VIEW';
export const PUT_DRILL_CARS_BLOCK_EDIT = 'PUT_DRILL_CARS_BLOCK_EDIT';
export const PUT_DRILL_CARS_BLOCK_EDIT_SINGLE = 'PUT_DRILL_CARS_BLOCK_EDIT_SINGLE';
export const PUT_DRILL_CARS_EDIT_ITEM_TO_SAVE = 'PUT_DRILL_CARS_EDIT_ITEM_TO_SAVE';
export const PUT_DRILL_CARS_EDIT_ITEM_TO_SAVE_EMPTY = 'PUT_DRILL_CARS_EDIT_ITEM_TO_SAVE_EMPTY';
export const PUT_DRILL_SUPPLY = 'PUT_DRILL_SUPPLY';
export const PUT_DRILL_SUPPLY_SET = 'PUT_DRILL_SUPPLY_SET';
export const PUT_DRILL_SUPPLY_SET_EDIT = 'PUT_DRILL_SUPPLY_SET_EDIT';
export const PUT_DRILL_SUPPLY_SET_INIT = 'PUT_DRILL_SUPPLY_SET_INIT';
export const PUT_DRILL_MAIN_STAFF = 'PUT_DRILL_MAIN_STAFF';
export const PUT_DRILL_MAIN_STAFF_CURRENT_SET = 'PUT_DRILL_MAIN_STAFF_CURRENT_SET';
export const PUT_DRILL_MAIN_STAFF_CURRENT_ITEM = 'PUT_DRILL_MAIN_STAFF_CURRENT_ITEM';
export const PUT_DRILL_LAST_SAVE = 'PUT_DRILL_LAST_SAVE';
export const PUT_DRILL_LAST_SAVE_FLAG_GLOBAL = 'PUT_DRILL_LAST_SAVE_FLAG_GLOBAL';
export const PUT_DRILL_LAST_SAVE_CURRENT_SET = 'PUT_DRILL_LAST_SAVE_CURRENT_SET';
export const PUT_DRILL_SAVE_FLAGS_CURRENT_SET = 'PUT_DRILL_SAVE_FLAGS_CURRENT_SET';

// drillHistory
export const PUT_DRILL_HISTORY_DUTY_NUMBER = 'PUT_DRILL_HISTORY_DUTY_NUMBER';
export const PUT_DRILL_HISTORY_DUTY_WORK_DAY = 'PUT_DRILL_HISTORY_DUTY_WORK_DAY';
export const PUT_DRILL_HISTORY_STATIONS = 'PUT_DRILL_HISTORY_STATIONS';
export const SELECT_DRILL_HISTORY_STATION = 'SELECT_DRILL_HISTORY_STATION';
export const SELECT_DRILL_HISTORY_STATION_FLAG = 'SELECT_DRILL_HISTORY_STATION_FLAG';
export const PUT_DRILL_HISTORY_STATS = 'PUT_DRILL_HISTORY_STATS';
export const PUT_DRILL_HISTORY_DATASET = 'PUT_DRILL_HISTORY_DATASET';
export const PUT_DRILL_HISTORY_DATASET_STATION = 'PUT_DRILL_HISTORY_DATASET_STATION';
export const PUT_DRILL_HISTORY_CARS_BLOCK_VIEW = 'PUT_DRILL_HISTORY_CARS_BLOCK_VIEW';

// tasks
export const PUT_TASKS_DRILL_DATA = 'PUT_TASKS_DRILL_DATA';
export const SELECT_TASKS_CALLCENTER = 'SELECT_TASKS_CALLCENTER';
export const SELECT_TASKS_CALLCENTER_ID = 'SELECT_TASKS_CALLCENTER_ID';
export const SELECT_TASKS_CALLCENTER_FLAG = 'SELECT_TASKS_CALLCENTER_FLAG';
export const PUT_TASKS_STATIONS = 'PUT_TASKS_STATIONS';
export const SELECT_TASKS_STATION = 'SELECT_TASKS_STATION';
export const SELECT_TASKS_STATION_ID = 'SELECT_TASKS_STATION_ID';
export const PUT_TASKS_STATIONS_LISTS_FLAG = 'PUT_TASKS_STATIONS_LISTS_FLAG';
export const SELECT_TASKS_STATION_FLAG = 'SELECT_TASKS_STATION_FLAG';
export const PUT_TASKS_REGISTRY_HEIGHT = 'PUT_TASKS_REGISTRY_HEIGHT';
export const PUT_TASKS_REGISTRY_TAB = 'PUT_TASKS_REGISTRY_TAB';
export const PUT_TASKS_REGISTRY_CURRENT = 'PUT_TASKS_REGISTRY_CURRENT';
export const PUT_TASKS_REGISTRY_CURRENT_FILTERED = 'PUT_TASKS_REGISTRY_CURRENT_FILTERED';
export const PUT_TASKS_REGISTRY_HISTORY = 'PUT_TASKS_REGISTRY_HISTORY';
export const PUT_TASKS_REGISTRY_HISTORY_FILTERED = 'PUT_TASKS_REGISTRY_HISTORY_FILTERED';
export const PUT_TASKS_REGISTRY_HISTORY_PERIOD = 'PUT_TASKS_REGISTRY_HISTORY_PERIOD';
export const PUT_TASKS_REGISTRY_HISTORY_PERIOD_LABEL = 'PUT_TASKS_REGISTRY_HISTORY_PERIOD_LABEL';
export const PUT_TASKS_REGISTRY_CURRENT_RECORD_ID = 'PUT_TASKS_REGISTRY_CURRENT_RECORD_ID';
export const PUT_TASKS_REGISTRY_HISTORY_RECORD_ID = 'PUT_TASKS_REGISTRY_HISTORY_RECORD_ID';
export const PUT_TASKS_WINDOW_STATE = 'PUT_TASKS_WINDOW_STATE';
export const PUT_TASKS_FORM_EDIT_STATE = 'PUT_TASKS_FORM_EDIT_STATE';
export const PUT_TASKS_FORM_EDIT_TYPE = 'PUT_TASKS_FORM_EDIT_TYPE';

// tasksEdit
export const PUT_TASKS_FORM_EDIT = 'PUT_TASKS_FORM_EDIT';
export const PUT_TASKS_FORM_EDIT_CALLCENTER_ID = 'PUT_TASKS_FORM_EDIT_CALLCENTER_ID';
export const PUT_TASKS_FORM_EDIT_STATION_ID = 'PUT_TASKS_FORM_EDIT_STATION_ID';
export const PUT_TASKS_FORM_EDIT_DATE = 'PUT_TASKS_FORM_EDIT_DATE';
export const PUT_TASKS_FORM_EDIT_TIME = 'PUT_TASKS_FORM_EDIT_TIME';
export const PUT_TASKS_FORM_EDIT_CALLER = 'PUT_TASKS_FORM_EDIT_CALLER';
export const PUT_TASKS_FORM_EDIT_CALLER_INIT = 'PUT_TASKS_FORM_EDIT_CALLER_INIT';
export const PUT_TASKS_FORM_EDIT_PLACE = 'PUT_TASKS_FORM_EDIT_PLACE';
export const PUT_TASKS_FORM_EDIT_PLACE_INIT = 'PUT_TASKS_FORM_EDIT_PLACE_INIT';
export const REFRESH_TASKS_FORM_EDIT_PLACE = 'REFRESH_TASKS_FORM_EDIT_PLACE';
export const PUT_TASKS_FORM_EDIT_CAUSE = 'PUT_TASKS_FORM_EDIT_CAUSE';
export const PUT_TASKS_FORM_EDIT_CAUSE_INIT = 'PUT_TASKS_FORM_EDIT_CAUSE_INIT';
export const REFRESH_TASKS_FORM_EDIT_CAUSE = 'REFRESH_TASKS_FORM_EDIT_CAUSE';
export const PUT_TASKS_SUB_TYPES = 'PUT_TASKS_SUB_TYPES';
export const PUT_TASKS_FORM_EDIT_EXTRA_INFO = 'PUT_TASKS_FORM_EDIT_EXTRA_INFO';
export const PUT_TASKS_FORM_EDIT_EXTRA_INFO_INIT = 'PUT_TASKS_FORM_EDIT_EXTRA_INFO_INIT';
export const REFRESH_TASKS_FORM_EDIT_EXTRA_INFO = 'REFRESH_TASKS_FORM_EDIT_EXTRA_INFO';
export const PUT_TASKS_FORM_EDIT_STATS = 'PUT_TASKS_FORM_EDIT_STATS';
export const REFRESH_TASKS_FORM_EDIT_STATS = 'REFRESH_TASKS_FORM_EDIT_STATS';
export const PUT_TASKS_FORM_EDIT_SIGNAL_ATC = 'PUT_TASKS_FORM_EDIT_SIGNAL_ATC';
export const PUT_TASKS_FORM_EDIT_SIGNAL_ATC_INIT = 'PUT_TASKS_FORM_EDIT_SIGNAL_ATC_INIT';
export const PUT_TASKS_RECORD_HEIGHT = 'PUT_TASKS_RECORD_HEIGHT';

// tasksEditCars
export const PUT_TASKS_DRILL_COMBAT_CARS = 'PUT_TASKS_DRILL_COMBAT_CARS';
export const PUT_TASKS_BUSY_CARS = 'PUT_TASKS_BUSY_CARS';
export const PUT_TASKS_COMBAT_CARS_SELECT = 'PUT_TASKS_COMBAT_CARS_SELECT';
export const CHECK_TASKS_COMBAT_CARS_SELECTED = 'CHECK_TASKS_COMBAT_CARS_SELECTED';
export const PUT_TASKS_COMBAT_CARS_REGISTRY = 'PUT_TASKS_COMBAT_CARS_REGISTRY';
export const PUT_TASKS_FORM_EDIT_CARS_COMBAT_ITEM = 'PUT_TASKS_FORM_EDIT_CARS_COMBAT_ITEM';
export const PUT_TASKS_FORM_EDIT_CARS_COMBAT_ITEM_INIT = 'PUT_TASKS_FORM_EDIT_CARS_COMBAT_ITEM_INIT';
export const REFRESH_TASKS_FORM_EDIT_CARS_COMBAT_ITEM = 'REFRESH_TASKS_FORM_EDIT_CARS_COMBAT_ITEM';
export const PUT_TASKS_COMBAT_CARS_GROUP_EDIT = 'PUT_TASKS_COMBAT_CARS_GROUP_EDIT';
export const REFRESH_TASKS_COMBAT_CARS_GROUP_EDIT = 'REFRESH_TASKS_COMBAT_CARS_GROUP_EDIT';
export const PUT_TASKS_COMBAT_CARS_GROUP_EDIT_FIELD = 'PUT_TASKS_COMBAT_CARS_GROUP_EDIT_FIELD';
